# tasks file for 6551
- name: resoconto in file {{ logfile }}
  shell: echo "Applicato il bug {{bug}} dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
  delegate_to: localhost
  changed_when: false
- name: resoconto in database ansible
  shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
  delegate_to: localhost
  changed_when: false

#Il parametro DB è obbligatorio ma meglio ribadirlo
- block:
  - name: Fallisco l'applicazione del bugfix se non esiste il parametro DB
    fail: msg="Non posso procedere perchè non è presente il parametro DB"
  - meta: end_play
  when: DB is not defined

- include: controlli_database.yml
  when: inventory_hostname == DB

- shell: ps -C opensips
  changed_when: false
  failed_when: false
  check_mode: false
  register: opensips_up_6551

- name: Esiste il file di configurazione di opensips?
  stat: path=/etc/opensips/opensips.cfg
  register: cfg_opensips_presente_6551

- include: modifica_opensips.yml
  when:
  - opensips_up_6551.rc == 0
  - cfg_opensips_presente_6551.stat.exists
